apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: plausible

secretGenerator:
- envs:
  - plausible-conf.env.secret
  name: plausible-config
  options:
    disableNameSuffixHash: true

labels:
- includeSelectors: true
  pairs:
    app: plausible
