stages:
- configure
- deploy

configure:
  stage: configure
  image: mosstech/ci-tools:latest
  variables:
    GOOGLE_CREDENTIALS: "${K8S_CREDENTIALS}"
  only:
    refs:
    - master
    changes:
    - terraform/**/*
    - .gitlab-ci.yml
  before_script:
  - echo "${GOOGLE_CREDENTIALS}" | gcloud auth activate-service-account --key-file -
  - gcloud config set project "$(echo "${GOOGLE_CREDENTIALS}" | jq -r '.project_id')"
  script:
  - ./terraform.sh
  after_script:
  - gcloud auth revoke --verbosity=error


deploy:
  stage: deploy
  image: mosstech/ci-tools:latest
  only:
  - master
  before_script:
    - echo "${GOOGLE_CREDENTIALS}" | gcloud auth activate-service-account --key-file -
    - region=$(gcloud container clusters list --project=${GCP_PROJECT_ID} --filter "NAME=${CLUSTER_NAME}" --format "value(zone)")
    - gcloud container clusters get-credentials ${CLUSTER_NAME} --project=${GCP_PROJECT_ID} --region=${region}
  script:
    - ./deploy.sh

# TODO: Smoke Test