stages:
- deploy
- smoke

variables:
  POSTGRES_IMAGE: postgres:14-alpine
  CLICKHOUSE_IMAGE: clickhouse/clickhouse-server:24.5.1-alpine
  PLAUSIBLE_IMAGE: ghcr.io/plausible/community-edition:v2.1.0-rc.0
  GOOGLE_CREDENTIALS: "${APPLICATION_CI_CREDENTIALS}"

deploy-db:
  stage: deploy
  image: mosstech/ci-tools:latest
  rules:
      - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      - if: '$CI_PIPELINE_SOURCE == "pipeline" && $DEPLOY_PLAUSIBLE == "true"'
  before_script:
    - echo "${GOOGLE_CREDENTIALS}" | gcloud auth activate-service-account --key-file -
    - region=$(gcloud container clusters list --project=${GCP_PROJECT_ID} --filter "NAME=${CLUSTER_NAME}" --format "value(zone)")
    - gcloud container clusters get-credentials ${CLUSTER_NAME} --project=${GCP_PROJECT_ID} --region=${region}
  script:
    - ./deploy.sh plausible-db

deploy-events-db:
  stage: deploy
  image: mosstech/ci-tools:latest
  rules:
      - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      - if: '$CI_PIPELINE_SOURCE == "pipeline" && $DEPLOY_PLAUSIBLE == "true"'
  before_script:
    - echo "${GOOGLE_CREDENTIALS}" | gcloud auth activate-service-account --key-file -
    - region=$(gcloud container clusters list --project=${GCP_PROJECT_ID} --filter "NAME=${CLUSTER_NAME}" --format "value(zone)")
    - gcloud container clusters get-credentials ${CLUSTER_NAME} --project=${GCP_PROJECT_ID} --region=${region}
  script:
    - ./deploy.sh plausible-events-db

deploy-server:
  stage: deploy
  image: mosstech/ci-tools:latest
  rules:
      - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      - if: '$CI_PIPELINE_SOURCE == "pipeline" && $DEPLOY_PLAUSIBLE == "true"'
  before_script:
    - echo "${GOOGLE_CREDENTIALS}" | gcloud auth activate-service-account --key-file -
    - region=$(gcloud container clusters list --project=${GCP_PROJECT_ID} --filter "NAME=${CLUSTER_NAME}" --format "value(zone)")
    - gcloud container clusters get-credentials ${CLUSTER_NAME} --project=${GCP_PROJECT_ID} --region=${region}
  script:
    - ./deploy.sh plausible-server


smoke-test:
  stage: smoke
  image: mosstech/ci-tools:latest
  script:
    - ./smoke-test.sh
