workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
    - if: '$CI_PIPELINE_SOURCE == "pipeline" && $DEPLOY_PLAUSIBLE == "true"'

stages:
- configure
- deploy
- smoke

variables:
  GOOGLE_CREDENTIALS: "${APP_CI_CREDENTIALS}"

include:
  # deploy db
  - component: gitlab.com/alexos-dev/gitlab-ci-components/deploy-k8s@~latest
    inputs:
      job-stage: deploy
      job-suffix: db
      job-needs: ["configure"]
      app-name: plausible-db
      namespace: plausible
      image-name: postgres:16-alpine
      manifest-dir: k8s/plausible-db
      env-sub: '"\$PLAUSIBLE_DB_USER"'
      skip-rollout-check: "true"          # now managed by CNPG operator
      skip-image-tag: "true"
  # deploy events-db
  - component: gitlab.com/alexos-dev/gitlab-ci-components/deploy-k8s@~latest
    inputs:
      job-stage: deploy
      job-suffix: events-db
      job-needs: ["configure"]
      app-name: plausible-events-db
      namespace: plausible
      image-name: clickhouse/clickhouse-server:25.3.2-alpine
      manifest-dir: k8s/plausible-events-db
      rollout-type: statefulset
      skip-image-tag: "true"
  # deploy plausible
  - component: gitlab.com/alexos-dev/gitlab-ci-components/deploy-k8s@~latest
    inputs:
      job-stage: deploy
      job-suffix: plausible
      job-needs: ["deploy-k8s-db", "deploy-k8s-events-db"]
      app-name: plausible
      namespace: plausible
      image-name: ghcr.io/plausible/community-edition:v3.0.1
      manifest-dir: k8s/plausible-server
      skip-image-tag: "true"

configure:
  stage: configure
  image: mosstech/ci-tools:latest
  before_script:
    - echo "${GOOGLE_CREDENTIALS}" | gcloud auth activate-service-account --key-file -
    - region=$(gcloud container clusters list --project=${GCP_PROJECT_ID} --filter "NAME=${CLUSTER_NAME}" --format "value(zone)")
    - gcloud container clusters get-credentials ${CLUSTER_NAME} --project=${GCP_PROJECT_ID} --region=${region}
  script:
    - ./scripts/install-operator.sh
    - ./scripts/setup-secrets.sh

smoke-test:
  stage: smoke
  image: mosstech/ci-tools:latest
  needs:
  - deploy-k8s-plausible
  script:
    - ./scripts/smoke-test.sh
