---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plausible
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
    spec:
      restartPolicy: Always
      serviceAccountName: plausible
      automountServiceAccountToken: false
      nodeSelector:
        cloud.google.com/gke-spot: "true"
      terminationGracePeriodSeconds: 20
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      initContainers:
        - name: plausible-init
          image: plausible:SET_BY_CI
          command:
            - "/bin/sh"
            - "-c"
          args:
            - sleep 30 && /entrypoint.sh db createdb && /entrypoint.sh db migrate
          envFrom:
            - secretRef:
                name: plausible-config
            - secretRef:
                name: plausible-db-app
          env:
            - name: DATABASE_URL
              value: $(uri)                     # generated by CNPG, read from secret plausible-db-app
            - name: CLICKHOUSE_DATABASE_URL
              value: http://$(CLICKHOUSE_USER):$(CLICKHOUSE_PASSWORD)@$(PLAUSIBLE_EVENTS_DB_SERVICE_HOST):$(PLAUSIBLE_EVENTS_DB_SERVICE_PORT)/plausible
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            readOnlyRootFilesystem: false
            capabilities:
              drop:
              - ALL
      containers:
        - name: plausible
          image: plausible:SET_BY_CI
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: plausible-config
            - secretRef:
                name: plausible-db-app
          env:
            - name: DATABASE_URL
              value: $(uri)                     # generated by CNPG, read from secret plausible-db-app
            - name: CLICKHOUSE_DATABASE_URL
              value: http://$(CLICKHOUSE_USER):$(CLICKHOUSE_PASSWORD)@$(PLAUSIBLE_EVENTS_DB_SERVICE_HOST):$(PLAUSIBLE_EVENTS_DB_SERVICE_PORT)/plausible
            - name: CLICKHOUSE_SKIP_USER_SETUP  # recommended when upgrading from v2->v3
              value: "1"
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            readOnlyRootFilesystem: false
            capabilities:
              drop:
              - ALL
          resources:
            limits:
              memory: 1000Mi
            requests:
              memory: 1000Mi
              cpu: 100m
          # needed to comment out the probes last time to get it to deploy - turned out to need longer delay for liveness
          readinessProbe:
            httpGet:
              path: /api/health
              port: 8000
            initialDelaySeconds: 35
            failureThreshold: 6
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/health
              port: 8000
            initialDelaySeconds: 60
            failureThreshold: 3
            periodSeconds: 10
