---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plausible
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - secretName: plausible-tls
      hosts:
        - plausible.alexos.dev
  rules:
    - host: plausible.alexos.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: plausible
                port:
                  name: http
