---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: plausible

commonLabels:
  app: plausible
  name: plausible-server

resources:
  - deployment.yaml
  - ingress.yaml
  - service.yaml
