apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: plausible

resources:
- deployment.yaml
- ingress.yaml
- service.yaml
- smtp-config.yaml

labels:
- includeSelectors: true
  pairs:
    app: plausible
    name: plausible-server
