apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: plausible



resources:
- service.yaml
- stateful-set.yaml
- ../base/
labels:
- includeSelectors: true
  pairs:
    app: plausible
    name: plausible-db
