---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: plausible-db
spec:
  description: "Plausible Analytics PostgreSQL Database"
  imageName: ghcr.io/cloudnative-pg/postgresql:14
  instances: 1
  storage:
    size: 15Gi
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "250m"
  monitoring:
    enablePodMonitor: true
  managed:
    services:
      disabledDefaultServices: ["ro", "r"]
  bootstrap:
    initdb:
      database: plausible
      owner: alexos_pg
  enableSuperuserAccess: false
  # we do not use backup functionality of CNPG here, as having to do PVC snapshots for Clickhouse already anyway
