---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: plausible-db
spec:
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  serviceName: plausible-db
  template:
    spec:
      restartPolicy: Always
      priorityClassName: has-volume-constraints
      securityContext:
        runAsUser: 70
        runAsGroup: 70
        fsGroup: 70
      containers:
        - name: plausible-db
          image: postgres:$POSTGRES_VERSION
          imagePullPolicy: Always
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          envFrom:
            - secretRef:
                name: plausible-config
          env:
            - name: POSTGRES_DB
              value: plausible
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          securityContext:
            allowPrivilegeEscalation: false
          resources:
            limits:
              memory: 200Mi
            requests:
              memory: 50Mi
              cpu: 10m
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - pg_isready -d plausible -U $POSTGRES_USER
            initialDelaySeconds: 20
            failureThreshold: 6
            periodSeconds: 10
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - pg_isready -d plausible -U $POSTGRES_USER
            initialDelaySeconds: 30
            failureThreshold: 3
            periodSeconds: 10
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 15Gi
