---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: plausible-db
spec:
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  serviceName: plausible-db
  template:
    spec:
      restartPolicy: Always
      nodeSelector:
        cloud.google.com/gke-spot: "true"
      terminationGracePeriodSeconds: 25
      priorityClassName: has-volume-constraints
      securityContext:
        runAsUser: 70
        runAsGroup: 70
        fsGroup: 70
      volumes:
      - name: tmp-volume
        emptyDir: {}
      - name: run-volume
        emptyDir: {}
      containers:
        - name: plausible-db
          image: postgres:$POSTGRES_VERSION
          imagePullPolicy: Always
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
            - name: tmp-volume
              mountPath: /tmp
            - name: run-volume
              mountPath: /var/run/postgresql
          envFrom:
            - secretRef:
                name: plausible-config
          env:
            - name: POSTGRES_DB
              value: plausible
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            capabilities:
              drop:
              - ALL
          resources:
            limits:
              memory: 300Mi
              cpu: 100m
            requests:
              memory: 300Mi
              cpu: 10m
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - pg_isready -d plausible -U $POSTGRES_USER
            initialDelaySeconds: 20
            failureThreshold: 6
            periodSeconds: 10
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - pg_isready -d plausible -U $POSTGRES_USER
            initialDelaySeconds: 30
            failureThreshold: 3
            periodSeconds: 10
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 15Gi
