---
apiVersion: v1
kind: ConfigMap
metadata:
  name: plausible-events-db-config
data:
  clickhouse-config.xml: |
    <yandex>

        <!-- disable IPv6 -->
        <listen_host>0.0.0.0</listen_host>

        <logger>
            <level>warning</level>
            <console>true</console>
        </logger>

        <!-- Stop all the unnecessary logging -->
        <query_thread_log remove="remove"/>
        <query_log remove="remove"/>
        <text_log remove="remove"/>
        <trace_log remove="remove"/>
        <metric_log remove="remove"/>
        <asynchronous_metric_log remove="remove"/>
    </yandex>
  clickhouse-user-config.xml: |
    <yandex>
        <profiles>
            <default>
                <log_queries>0</log_queries>
                <log_query_threads>0</log_query_threads>
            </default>
        </profiles>
    </yandex>
