---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: plausible

commonLabels:
  app: plausible
  name: events-db

resources:
  - config-map.yaml
  - service.yaml
  - stateful-set.yaml
