apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: plausible



resources:
- config-map.yaml
- service.yaml
- stateful-set.yaml
- ../base/
labels:
- includeSelectors: true
  pairs:
    name: events-db
