---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: plausible-events-db
spec:
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  serviceName: plausible-events-db
  template:
    spec:
      restartPolicy: Always
      priorityClassName: has-volume-constraints
      securityContext:
        runAsUser: 101
        runAsGroup: 101
        fsGroup: 101
      containers:
        - name: plausible-events-db
          image: clickhouse/clickhouse-server:$CLICKHOUSE_VERSION
          imagePullPolicy: Always
          ports:
            - containerPort: 8123
              name: http
            - containerPort: 9000
              name: native
          volumeMounts:
            - name: data
              mountPath: /var/lib/clickhouse
            - name: config
              mountPath: /etc/clickhouse-server/config.d/logging.xml
              subPath: clickhouse-config.xml
              readOnly: true
            - name: config
              mountPath: /etc/clickhouse-server/users.d/logging.xml
              subPath: clickhouse-user-config.xml
              readOnly: true
          envFrom:
            - secretRef:
                name: plausible-config
          env:
            - name: CLICKHOUSE_DB
              value: plausible
            - name: CLICKHOUSE_LISTEN_HOST
              value: "0.0.0.0"
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 101
            runAsGroup: 101
          resources:
            limits:
              memory: 1Gi
              cpu: 250m     # autopilot minimum
            requests:
              memory: 1Gi
              cpu: 250m     # autopilot minimum
          readinessProbe:
            httpGet:
              path: /ping
              port: 8123
            initialDelaySeconds: 20
            failureThreshold: 6
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /ping
              port: 8123
            initialDelaySeconds: 30
            failureThreshold: 3
            periodSeconds: 10
      volumes:
        - name: config
          configMap:
            name: plausible-events-db-config
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 20Gi
