---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: plausible-events-db
spec:
  replicas: 1
  serviceName: plausible-events-db
  template:
    spec:
      restartPolicy: Always
      securityContext:
        runAsUser: 101
        runAsGroup: 101
        fsGroup: 101
      containers:
        - name: plausible-events-db
          image: yandex/clickhouse-server:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8123
          volumeMounts:
            - name: data
              mountPath: /var/lib/clickhouse
            - name: config
              mountPath: /etc/clickhouse-server/config.d/logging.xml
              subPath: clickhouse-config.xml
              readOnly: true
            - name: config
              mountPath: /etc/clickhouse-server/users.d/logging.xml"
              subPath: clickhouse-user-config.xml
              readOnly: true
          envFrom:
            - secretRef:
                name: plausible-config
          env:
            - name: CLICKHOUSE_DB
              value: plausible
          securityContext:
            allowPrivilegeEscalation: false
          resources:
            limits:
              memory: 2Gi
              cpu: 1500m
            requests:
              memory: 80Mi
              cpu: 10m
          readinessProbe:
            httpGet:
              path: /ping
              port: 8123
            initialDelaySeconds: 20
            failureThreshold: 6
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /ping
              port: 8123
            initialDelaySeconds: 30
            failureThreshold: 3
            periodSeconds: 10
      volumes:
        - name: config
          configMap:
            name: plausible-events-db-config
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 128Mi
          limits:
            storage: 20Gi
