---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: plausible

commonLabels:
  app: plausible

secretGenerator:
  - name: plausible-config
    envs:
      - plausible-conf.env.secret
