apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: plausible


secretGenerator:
- envs:
  - plausible-conf.env.secret
  name: plausible-config
labels:
- includeSelectors: true
  pairs:
    app: plausible
